#!/usr/bin/env python3
"""Emit cairn_relic_types.hpp: the relic (effigy) type for each kEffigies entry.

Palworld's effigies are all one map object as far as our extracted kEffigies goes
(GUID + position). But each is really a BP_LevelObject_Relic*_C actor whose class
default carries an EPalRelicType (0..12: CapturePower, MoveSpeed, ...). That type
is not per-instance, so it can't be read from the instance GUID alone -- it comes
from the actor's class, recovered offline from the L15 world cell + the 12 relic
CDOs in Pal-Windows.pak (see data/codegen/relic_types.json, produced by that pak
extraction). This script joins that type table onto relic_guids.json BY GUID and
emits a uint8_t array PARALLEL to kEffigies, in the same order.

Kept OUT of gen_cairn_data.py / the verify_parity round-trip on purpose: cairn_
data.hpp and its frozen inputs are unchanged, so that gate stays green. This is a
standalone, additive header. Re-run whenever relic_guids.json or relic_types.json
changes:

    python3 tools/codegen/gen_relic_types.py [--check]

--check regenerates in memory and compares to the committed header (for CI).
"""

import argparse
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
RELIC_GUIDS = REPO / "data/codegen/relic_guids.json"
RELIC_TYPES = REPO / "data/codegen/relic_types.json"
OUT = REPO / "cpp-mod/mods/CairnMap/src/cairn_relic_types.hpp"

# EPalRelicType (Pal_enums.hpp) -> display name. Index IS the enum value.
RELIC_TYPE_NAMES = [
    "Capture Power",          # 0
    "Hunger Reduction",       # 1
    "Swim Speed",             # 2
    "Food Decay Reduction",   # 3
    "Jump Power",             # 4
    "Glider Speed",           # 5
    "Climb Speed",            # 6
    "Ailment Resist",         # 7
    "Stamina Reduction",      # 8
    "Sphere Homing",          # 9
    "Exp Bonus",              # 10
    "Rainbow Passive Rate",   # 11
    "Move Speed",             # 12
]


def build():
    relic = json.loads(RELIC_GUIDS.read_text())["Relic"]
    types = json.loads(RELIC_TYPES.read_text())
    missing = [row[0] for row in relic if row[0] not in types]
    if missing:
        sys.exit(f"error: {len(missing)} relic GUID(s) have no type "
                 f"(first: {missing[0]}) -- re-run the pak extraction")
    seq = []
    for guid, *_ in relic:
        t = int(types[guid]["type"])
        if not (0 <= t < len(RELIC_TYPE_NAMES)):
            sys.exit(f"error: relic {guid} has out-of-range type {t}")
        seq.append(t)

    body = ",".join(str(t) for t in seq)
    names = ", ".join(f'L"{n}"' for n in RELIC_TYPE_NAMES)
    lines = [
        "// Generated by tools/codegen/gen_relic_types.py - DO NOT EDIT",
        "// Relic (effigy) type per kEffigies entry, SAME order as kEffigies",
        "// (data/codegen/relic_guids.json \"Relic\"). EPalRelicType 0..12.",
        "#pragma once",
        "#include <cstdint>",
        "#include <cstddef>",
        "",
        "namespace CairnMap::Data {",
        f"inline constexpr uint8_t kEffigyType[] = {{{body}}};",
        f"inline constexpr size_t kEffigyTypeCount = {len(seq)};",
        f"inline constexpr int kRelicTypeCount = {len(RELIC_TYPE_NAMES)};",
        f"inline constexpr const wchar_t* kRelicTypeName[] = {{{names}}};",
        "} // namespace CairnMap::Data",
        "",
    ]
    return "\n".join(lines), len(seq)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="compare to the committed header instead of writing")
    args = ap.parse_args()
    text, n = build()
    if args.check:
        if not OUT.exists():
            sys.exit(f"MISSING {OUT}")
        if OUT.read_text() != text:
            sys.exit(f"DRIFT {OUT} no longer matches relic_guids.json + relic_types.json")
        print(f"  ok      cairn_relic_types.hpp {n} effigy types")
    else:
        OUT.write_text(text)
        print(f"  wrote   {n} effigy types -> {OUT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
